const FILTER_TYPE_TEXT = "TEXT";
const FILTER_TYPE_DROP_DOWN = "DROP_DOWN";
const FILTER_TYPE_RADIO_BUTTON = "RADIO_BUTTON";

export {
  FILTER_TYPE_TEXT,
  FILTER_TYPE_DROP_DOWN,
  FILTER_TYPE_RADIO_BUTTON,
}
